### ISSUE TITLE
Add "use strict" as an option for minispade filter

### ISSUE THREAD

**Issue by jamesarosen** [wycats/rake-pipeline-web-filters#1]
It's a good general practice to add `"use strict";` to the top of each major function. It would be nice to have a `strict` option on the filter that would add it just inside the `function() { }` wrapper.

Why not just have the user put it in each source file? Because global `"use strict";` is a bad idea, so things like JSHint expect it to be inside a `function() {}()` call. To do this in the source files means that each source file would have to look like

``` javascript
(function() {
  "use strict";
  ...
}());
```

which would then get compiled to

``` javascript
minispade.register('filename', function() {
  (function() {
    "use strict";
    ...
  }());
});
```

There's nothing _wrong_ with that, but it seems wasteful.

**Comment by wagenet** [comment]
Seems fine to set up some options for minispade filter. I suspect you're well equipped to make a pull request for that :)
