### ISSUE TITLE
UglifyJS bug fix not included

### ISSUE THREAD

**Issue by bobspryn** [wycats/rake-pipeline-web-filters#12]
https://github.com/mishoo/UglifyJS/issues/126

So this is probably more of a Ruby gem issue than here, but uglifyjs is stripping the last semicolon of the file, which generates a very hard to find bug when concatenating file together. Looks like it was fixed but the latest ruby gem hasn't pulled it in. Perhaps we can work around it until then?

**Comment by dudleyf** [comment]
Yeah, this is a bug in the uglifier gem. The version of uglifyjs they're using includes that fix, so I'm not sure what's going on there.

**Comment by bobspryn** [comment]
for now just use a simple stupid filter to get around this:

```
class FixUglifyFilter < Rake::Pipeline::Filter
  def generate_output(inputs, output)
    inputs.each do |input|
      output.write input.read + ";"
    end
  end
end
```

**Comment by ahawkins** [comment]
Just need to require "~> 1.2.3". It's been fixed in that uglifier patch version.

**Comment by bobspryn** [comment]
Sweet. It'll be nice to get rid of that extra filter.
