### ISSUE TITLE
Uglify filter forgets to insert ";" at the end of the file

### ISSUE THREAD

**Issue by ppcano** [wycats/rake-pipeline-web-filters#24]
I use the filter shown below to fix the problems, copied from the following [gist](https://gist.github.com/1848601)

``` javascript
class FixUglifyFilter < Rake::Pipeline::Filter
  def generate_output(inputs, output)
    inputs.each do |input|
      output.write input.read + ";"
    end
  end
end
```

**Comment by dudleyf** [comment]
This was reported in issue #12. It's a bug in the uglifier gem that was fixed in the latest release.
