### ISSUE TITLE
Changes to @import[ed] files in SASS filter won't update server

### ISSUE THREAD

**Issue by sandstrom** [wycats/rake-pipeline-web-filters#31]
**foo.scss**

```
@import "bar";
```

**_bar.scss**

```
body { color: green; }
```

Steps to reproduce:
1. add the files above
2. run `rakep server`
3. change _bar.scss
4. reload website (without restarting the server)
5. the change won't show (unless foo.scss is modified/touched too)

**Comment by dudleyf** [comment]
If _bar.scss isn't an input to the pipeline, rakep doesn't know that foo.scss depends on it. The Sass filter adds files from `:additional_load_paths` to the dependencies for each Sass file, so if you pass the directory containing _bar.scss into `:additional_load_paths` when you call the Sass filter, it should work:

``` ruby
# Assuming _bar.scss is in 'scss/_bar.scss'
scss :additional_load_paths => ['scss']
```

**Comment by sandstrom** [comment]
@dudleyf thanks! I added "." to the path and it worked. (though I could import them before which is strange, anyway it works now)

**Comment by dudleyf** [comment]
Yeah, if they're in the current directory, Sass's `@import` will find them, but the Sass filter won't add them to the dependencies. So in this case, passing in the `:additional_load_paths` is just a workaround to force the filter to notice the extra dependencies.
