### ISSUE TITLE
Release a new gem version

### ISSUE THREAD

**Issue by lukemelia** [wycats/rake-pipeline-web-filters#37]
The most recent version on rubygems is 0.5.0 from December 2011. There are a number of valuable new filters available now.

**Comment by dudleyf** [comment]
Agreed. @wycats?

**Comment by ahawkins** [comment]
Agreed. We need this for Iridium

**Comment by trek** [comment]
+1

got majorly bit by forgetting to use the git version.

**Comment by jordanstephens** [comment]
+1

**Comment by lukemelia** [comment]
It has dropped!
