### ISSUE TITLE
Requesting a web filter for minifying

### ISSUE THREAD

**Issue by bobspryn** [wycats/rake-pipeline-web-filters#5]
A web filter for minifying javascript/css would be awesome.

**Comment by dudleyf** [comment]
We added YUI for js in 145c1f4feab2a5e2686cff9f3646d30947e33636, I'm leaving this open to remind me to do one for CSS.

**Comment by dudleyf** [comment]
Added a CSS compressor in 91df9ad9fd50fc30cc363bb6d7c006888bb109e1.
