### ISSUE TITLE
Remove OrderingConcatFilter

### ISSUE THREAD

**Issue by dudleyf** [wycats/rake-pipeline-web-filters#6]
Rake::Pipeline::Web::Filters::OrderingConcatFilter has moved to rake-pipeline. Do we need to worry about deprecations at this point, or can we just drop the old one?

**Comment by dudleyf** [comment]
I'd also like to change all the filter classes to have consistent naming (e.g OctopusCompiler to OctopusFilter) so people don't have to remember whether it's a SassCompiler or a SassConverter, etc. @wycats, @jamesarosen, @wagenet, what do you guys think?

**Comment by wycats** [comment]
I agree with both requests. Pull request?

**Comment by jamesarosen** [comment]
Agreed. Nice work.
